const ZH: Readonly<Record<string, string>> = Object.freeze({
  "Proposal Assistant": "提案助手",
  "AI-requested decision · your answer returns to the agent": "确认你的选择后，继续准备提案",
  "Proposal setup": "提案准备",
  "AI-selected question": "需要你确认",
  "Proposal context": "提案信息",
  "Application preview": "用途预览",
  "Application": "适用场景",
  "Primary audience": "主要读者",
  "Core story": "内容结构",
  "Visual style is selected in the next AI-requested step.": "确认用途后，继续选择演示风格。",
  "Deck style preview": "演示风格预览",
  "3-slide style system": "三页风格示例",
  "Best for": "适合场景",
  "Story rhythm": "叙事顺序",
  "Preview by hover or focus. After style confirmation, the Agent matches capabilities and offers available content and data.": "悬停或用键盘聚焦可查看预览。确认风格后，继续选择需要的内容与资料。",
  "Category Analysis": "类目分析",
  "Internal Kick Off": "内部启动会",
  "Line Review Proposal": "商品提案",
  "Strategy Consulting": "策略咨询",
  "Paramont Signature": "品牌经典",
  "Playful Storybook": "趣味故事",
  "Beauty Care": "美妆护理",
  "Stationery": "文具",
  "Holiday Events": "节庆用品",
  "Dollar General": "Dollar General 零售商",
  "Walmart": "沃尔玛",
  "Value retail · U.S. mass-market footprint": "面向美国大众市场的折扣零售商",
  "Omnichannel retail · enterprise scale": "覆盖线上与线下的大型零售商",
  "Cosmetics & Cosmetic Tools": "化妆品与美妆工具",
  "Stickers & Creative Crafts": "贴纸与创意手工",
  "Party Favors & Balloons": "派对小礼品与气球",
  "Performance data, opportunity gaps and annual direction": "经营表现、市场机会与年度方向",
  "Internal alignment for Sales, Category and Product Development": "明确销售、类目与产品开发团队的共同目标",
  "Formal category and line recommendation for customer buyers": "面向采购方的类目分析与商品建议",
  "Answer-first logic, sharp charts and executive clarity": "结论清楚，图表简洁，适合管理层决策",
  "Official mountain identity with a confident enterprise system": "沿用正式山形品牌元素，适合企业提案",
  "Colorful illustrated storytelling for family and youth audiences": "使用丰富插画，适合家庭与年轻读者",
  "Performance analysis": "经营分析",
  "Use performance data to clarify annual development direction, category gaps and priority opportunities.": "根据经营数据明确年度方向、类目缺口与优先机会。",
  "Category, development and leadership teams": "类目、产品开发与管理团队",
  "Performance baseline · Opportunity gaps · Annual direction": "经营现状 · 机会缺口 · 年度方向",
  "Internal alignment": "团队共识",
  "Align Sales, Category and Product Development on targeted strategic metrics and the work ahead.": "明确销售、类目与产品开发团队的目标指标和后续工作。",
  "Sales, Category and Product Development teams": "销售、类目与产品开发团队",
  "Why now · Strategic metrics · Workstreams · Owners": "开展原因 · 目标指标 · 工作安排 · 负责人",
  "Buyer presentation": "采购提案",
  "Present the category case, recommended line and commercial rationale to customer procurement teams.": "向采购团队说明类目机会、推荐商品与商业依据。",
  "Customer buyers and procurement stakeholders": "客户采购团队与相关决策者",
  "Category opportunity · Line recommendation · Commercial case": "类目机会 · 商品建议 · 商业依据",
  "Board reviews and executive decisions": "董事会评审与管理层决策",
  "Answer first · Proof · Action": "结论 · 依据 · 行动",
  "A disciplined white-space system with sharp analysis, cobalt charts and restrained red emphasis.": "留白清晰，以蓝色图表呈现分析，少量红色强调重点。",
  "Strategy consulting storyboard with answer-first headlines and analytical charts": "策略咨询风格示例：先呈现结论，再展示分析图表",
  "Paramont-owned client and leadership stories": "品牌客户提案与管理汇报",
  "Altitude · Opportunity · Decision": "全局视角 · 机会 · 决策",
  "The official mountain identity translated into an ice-blue, midnight and white presentation system.": "沿用正式山形标识，搭配冰蓝、深蓝与白色。",
  "Paramont Signature storyboard with official mountain identity and enterprise slides": "品牌经典风格示例：正式山形标识与企业演示页面",
  "Family, children and youth-facing concepts": "面向家庭、儿童与年轻人的创意方案",
  "World · Wonder · Possibility": "场景 · 发现 · 可能性",
  "A bright cut-paper illustration system with warm characters, rounded forms and joyful color.": "明亮的剪纸插画、亲切人物、圆润造型与活泼配色。",
  "Playful storybook storyboard with colorful cut-paper illustrations and children": "趣味故事风格示例：彩色剪纸插画与儿童形象",
  "Sending your answer to Proposal Assistant…": "正在提交你的选择…",
  "Proposal Assistant is pausing this intake…": "正在取消本次提案准备…",
  "Proposal Assistant is deciding which earlier context to revisit…": "正在返回上一步…",
  "Use selected content": "使用所选内容",
  "Use this deck style": "使用此风格",
  "Use this deck type": "使用此用途",
  "Continue": "继续",
  "Select the content and data to include": "选择需要的内容和资料",
  "Preview and select one style": "预览并选择一种风格",
  "Preview and select one deck type": "预览并选择一种用途",
  "Select an option to continue": "选择后继续",
  "Available from matched capability": "可用内容",
  "Recommended": "推荐",
  "Enter another option": "输入其他选择",
  "Back": "返回",
  "Cancel proposal question": "取消提案准备",
  "Cancel intake": "取消准备"
})

export function proposalText(value: string, zh: boolean): string {
  return zh ? ZH[value] ?? value : value
}
