import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { McpCenterSection, type McpRemoteApi } from '../src/client/index.js'
import { McpConnectionPicker } from '../../agent-market/src/client/mcp-picker.js'
import type { McpConnectionView } from '../src/contract.js'
afterEach(cleanup)
const id = 'a'.repeat(32)
const view: McpConnectionView = { connection: { configuration: { id, name: '我的飞书', category: 'documents', enabled: true, timeoutMs: 60000, transport: 'stdio', command: 'node', args: [], cwd: '/tmp', envRefs: {} }, owner: 'local', revision: 1, updatedAt: 1 }, state: 'available', tools: [{ name: 'read', description: 'Read' }], probe: { at: 1, status: 'passed', message: '协议握手成功；尚未验证文档权限。' }, business: null, bindings: [{ presetId: 'writer', name: '写作助手' }] }
function api() {
 return { list: vi.fn(async () => ({ ok: true, value: { items: [view] } })), save: vi.fn(async () => ({ ok: true, value: view })), probe: vi.fn(async () => ({ ok: true, value: view })), setEnabled: vi.fn(async () => ({ ok: true, value: view })), removeConnection: vi.fn(async () => ({ ok: true, value: { removed: true } })), templates: vi.fn(async () => ({ ok: true, value: { items: [] } })) } as unknown as McpRemoteApi
}
it('searches and filters connections, distinguishes probe from business evidence, reviews impacted Agents before removal', async () => {
 const remote = api(); render(<McpCenterSection api={remote} />)
 await screen.findByText('我的飞书')
 fireEvent.change(screen.getByLabelText('搜索连接'), { target: { value: '不存在' } }); expect(screen.getByText('没有匹配的连接')).toBeTruthy()
 fireEvent.change(screen.getByLabelText('搜索连接'), { target: { value: '' } })
 fireEvent.change(screen.getByLabelText('按用途筛选'), { target: { value: 'data' } }); expect(screen.getByText('没有匹配的连接')).toBeTruthy()
 fireEvent.change(screen.getByLabelText('按用途筛选'), { target: { value: 'documents' } })
 fireEvent.click(screen.getByRole('button', { name: '查看详情' }))
 expect(screen.getByText(/尚无真实调用证据/)).toBeTruthy()
 fireEvent.click(screen.getByRole('button', { name: '测试连接' }))
 await waitFor(() => expect(remote.probe).toHaveBeenCalledWith({ id, expectedRevision: 1 }))
 await waitFor(() => expect(screen.getByRole('button', { name: '移除' })).not.toBeDisabled())
 fireEvent.click(screen.getByRole('button', { name: '移除' }))
 expect(screen.getByRole('alertdialog').textContent).toContain('写作助手')
 expect(remote.removeConnection).not.toHaveBeenCalled()
 fireEvent.click(screen.getByRole('button', { name: '确认移除' }))
 await waitFor(() => expect(remote.removeConnection).toHaveBeenCalledWith({ id, expectedRevision: 1, acknowledgeBindings: true }))
})
it('never silently changes Agent references when the connection center is unavailable', async () => {
 const change = vi.fn(); render(<McpConnectionPicker selected={[id]} onChange={change} />)
 fireEvent.click(screen.getByRole('button', { name: /工具连接（可选）/ }))
 expect(await screen.findByRole('alert')).toHaveTextContent('已保存引用保持不变')
 expect(change).not.toHaveBeenCalled()
})
it('allows explicit unbinding of a missing reference', async () => {
 const remote = api(), missing = 'b'.repeat(32), change = vi.fn()
 render(<McpConnectionPicker api={remote} selected={[missing]} onChange={change} />)
 fireEvent.click(screen.getByRole('button', { name: /工具连接（可选）/ }))
 const checkbox = await screen.findByRole('checkbox', { name: /不可用的连接/ })
 fireEvent.click(checkbox); expect(change).toHaveBeenCalledWith([])
})

it('uses generic remote templates and scopes setup hints to the selected template', async () => {
 const remote = api()
 vi.mocked(remote.templates).mockResolvedValue({ ok: true, value: { items: [{ id: 'generic', name: '数据查询', description: 'Remote tools', setupHint: '使用服务自己的账号', configuration: { transport: 'streamable-http', url: 'https://example.invalid/mcp', headerRefs: {}, category: 'data', enabled: true, timeoutMs: 5000 } }] } })
 render(<McpCenterSection api={remote} />)
 fireEvent.click(screen.getByRole('button', { name: '添加连接', exact: true }))
 fireEvent.click(await screen.findByRole('button', { name: /数据查询/ }))
 expect(screen.getByLabelText('服务地址')).toHaveValue('https://example.invalid/mcp')
 expect(screen.getByText('使用服务自己的账号')).toBeTruthy()
 fireEvent.click(screen.getByRole('button', { name: '关闭', exact: true }))
 fireEvent.click(screen.getByRole('button', { name: '添加连接', exact: true }))
 expect(screen.queryByText('使用服务自己的账号')).toBeNull()
 fireEvent.click(screen.getByRole('button', { name: /本地程序/ }))
 expect(screen.getByLabelText('启动程序')).toHaveValue('')
})
it('filters connection choices without losing selected references and keeps disabled choices unavailable', async () => {
 const remote = api(), change = vi.fn()
 vi.mocked(remote.list).mockResolvedValue({ ok: true, value: { items: [view, { ...view, connection: { ...view.connection, configuration: { ...view.connection.configuration, id: 'b'.repeat(32), name: '已停用数据服务', enabled: false, category: 'data' } }, state: 'disabled' }] } })
 render(<McpConnectionPicker api={remote} selected={[id]} onChange={change} />)
 const panel = screen.getByRole('button', { name: /工具连接（可选）/ })
 expect(panel).toHaveAttribute('aria-expanded', 'false')
 fireEvent.click(panel)
 expect(await screen.findByRole('checkbox', { name: /已停用数据服务/ })).toBeDisabled()
 fireEvent.change(screen.getByLabelText('搜索工具连接'), { target: { value: '不存在' } })
 expect(screen.getByText('当前筛选没有匹配连接。')).toBeTruthy()
 expect(change).not.toHaveBeenCalled()
 fireEvent.change(screen.getByLabelText('搜索工具连接'), { target: { value: '' } })
 fireEvent.click(screen.getByRole('button', { name: '只看已选 1' }))
 expect(screen.queryByRole('checkbox', { name: /已停用数据服务/ })).toBeNull()
 fireEvent.click(screen.getByRole('checkbox', { name: /我的飞书/ }))
 expect(change).toHaveBeenCalledWith([])
})

it('uses a generic English add flow without changing existing identities or Agent bindings', async () => {
 const remote = api()
 const locale = { subscribe: () => () => {}, getLocale: () => ({ active: 'en' }) } as Parameters<typeof McpCenterSection>[0]['locale']
 render(<McpCenterSection api={remote} locale={locale} />)
 await screen.findByText('我的飞书')
 expect(screen.getByRole('heading', { name: 'MCP Center' })).toBeTruthy()
 expect(screen.getAllByText('Tools available').length).toBeGreaterThan(0)
 fireEvent.click(screen.getByRole('button', { name: 'View details' }))
 expect(screen.getByText(/Used by agents:.*写作助手/)).toBeTruthy()
 fireEvent.click(screen.getByRole('button', { name: 'Add connection', exact: true }))
 fireEvent.click(screen.getByRole('button', { name: /Remote server/ }))
 expect(screen.getByLabelText('Service URL')).toHaveValue('')
 fireEvent.change(screen.getByLabelText('Connection name'), { target: { value: 'Remote tools' } })
 fireEvent.change(screen.getByLabelText('Service URL'), { target: { value: 'https://example.invalid/mcp' } })
 fireEvent.click(screen.getByRole('button', { name: 'Save connection' }))
 await waitFor(() => expect(remote.save).toHaveBeenCalled())
 const saved = vi.mocked(remote.save).mock.calls[0]![0]
 expect(saved.configuration.transport).toBe('streamable-http')
 expect(saved.configuration).not.toHaveProperty('command')
 expect(saved.configuration.id).not.toBe(id)
 expect(remote.setEnabled).not.toHaveBeenCalled()
 expect(remote.removeConnection).not.toHaveBeenCalled()
})

it('shows pending and failed probe results on the card without opening details', async () => {
 const remote = api()
 vi.mocked(remote.list).mockResolvedValue({ ok: true, value: { items: [{ ...view, probe: null, state: 'untested' }] } })
 let finish!: (result: Awaited<ReturnType<McpRemoteApi['probe']>>) => void
 vi.mocked(remote.probe).mockImplementation(() => new Promise(resolve => { finish = resolve }))
 render(<McpCenterSection api={remote} />)
 fireEvent.click(await screen.findByRole('button', { name: '测试连接' }))
 expect(screen.getByRole('button', { name: '正在测试…' })).toBeDisabled()
 expect(screen.getByRole('status')).toHaveTextContent('正在测试连接…')
 await act(async () => { finish({ ok: true, value: { ...view, state: 'error', probe: { at: Date.now(), status: 'failed', message: '无法连接目标服务，请检查地址、端口与网络。' } } }) })
 expect(screen.getByRole('status')).toHaveTextContent('最近测试失败')
 expect(screen.getByRole('status')).toHaveTextContent('无法连接目标服务')
 expect(screen.getByRole('button', { name: '查看详情' })).toHaveAttribute('aria-expanded', 'false')
 expect(remote.setEnabled).not.toHaveBeenCalled()
 expect(remote.removeConnection).not.toHaveBeenCalled()
})

it('tests a new unsaved local draft, preserves failures and saves only after an explicit save', async () => {
 const remote = api()
 let finish!: (result: Awaited<ReturnType<McpRemoteApi['probeDraft']>>) => void
 remote.probeDraft = vi.fn(() => new Promise(resolve => { finish = resolve }))
 render(<McpCenterSection api={remote} />)
 await screen.findByText('我的飞书')
 fireEvent.click(screen.getByRole('button', { name: '添加连接' }))
 fireEvent.click(screen.getByRole('button', { name: /本地程序/ }))
 const form = within(screen.getByRole('form', { name: '连接配置' }))
 fireEvent.change(form.getByLabelText('连接名称'), { target: { value: '未保存服务' } })
 fireEvent.change(form.getByLabelText('启动程序'), { target: { value: 'custom-server' } })
 fireEvent.change(form.getByLabelText('工作目录'), { target: { value: '/tmp' } })
 fireEvent.change(form.getByLabelText('启动参数（JSON 数组）'), { target: { value: '["--read-only"]' } })
 fireEvent.click(form.getByRole('button', { name: '测试连接' }))
 expect(form.getByRole('status')).toHaveTextContent('正在测试连接')
 expect(form.getByRole('button', { name: '保存连接' })).toBeDisabled()
 expect(remote.probeDraft).toHaveBeenCalledWith({ configuration: expect.objectContaining({ name: '未保存服务', command: 'custom-server', args: ['--read-only'], cwd: '/tmp' }) })
 expect(remote.save).not.toHaveBeenCalled()
 await act(async () => { finish({ ok: true, value: { tools: [], evidence: { at: 1, status: 'failed', message: '未找到启动程序或工作目录，请检查本机路径。' } } }) })
 expect(form.getByRole('status')).toHaveTextContent('当前配置测试失败')
 expect(form.getByLabelText('连接名称')).toHaveValue('未保存服务')
 expect(remote.save).not.toHaveBeenCalled()
 fireEvent.change(form.getByLabelText('启动程序'), { target: { value: 'fixed-server' } })
 expect(form.getByRole('status')).toHaveTextContent('配置已修改')
 fireEvent.click(form.getByRole('button', { name: '测试连接' }))
 await act(async () => { finish({ ok: true, value: { tools: [], evidence: { at: 2, status: 'passed', message: '协议握手成功，发现 0 个工具；未执行工具调用，具体操作权限尚待核验。' } } }) })
 expect(form.getByRole('status')).toHaveTextContent('当前配置测试通过')
 expect(remote.save).not.toHaveBeenCalled()
 fireEvent.click(form.getByRole('button', { name: '保存连接' }))
 await waitFor(() => expect(remote.save).toHaveBeenCalledWith({ configuration: vi.mocked(remote.probeDraft).mock.calls[1]![0].configuration, expectedRevision: 0 }))
 expect(remote.probe).not.toHaveBeenCalled()
 expect(remote.setEnabled).not.toHaveBeenCalled()
})

it('validates the form and JSON before probing, localizes failures and invalidates edited results', async () => {
 const remote = api()
 remote.probeDraft = vi.fn(async () => ({ ok: true, value: { tools: [], evidence: { at: 1, status: 'passed', message: '协议握手成功，发现 0 个工具；未执行工具调用，具体操作权限尚待核验。' } } }))
 const locale = { subscribe: () => () => {}, getLocale: () => ({ active: 'en' }) } as Parameters<typeof McpCenterSection>[0]['locale']
 render(<McpCenterSection api={remote} locale={locale} />)
 fireEvent.click(await screen.findByRole('button', { name: 'Edit' }))
 const form = within(screen.getByRole('form', { name: 'Connection configuration' }))
 fireEvent.change(form.getByLabelText('Command'), { target: { value: '' } })
 fireEvent.click(form.getByRole('button', { name: 'Test connection' }))
 expect(remote.probeDraft).not.toHaveBeenCalled()
 fireEvent.change(form.getByLabelText('Command'), { target: { value: 'node' } })
 fireEvent.change(form.getByLabelText('Arguments (JSON array)'), { target: { value: '[' } })
 fireEvent.click(form.getByRole('button', { name: 'Test connection' }))
 await waitFor(() => expect(form.getByRole('status')).toHaveTextContent('valid JSON array'))
 expect(remote.probeDraft).not.toHaveBeenCalled()
 fireEvent.change(form.getByLabelText('Arguments (JSON array)'), { target: { value: '["draft.js"]' } })
 fireEvent.click(form.getByRole('button', { name: 'Test connection' }))
 await waitFor(() => expect(form.getByRole('status')).toHaveTextContent('Current configuration passed'))
 expect(vi.mocked(remote.probeDraft).mock.calls[0]![0].configuration.id).toBe(id)
 fireEvent.change(form.getByLabelText('Arguments (JSON array)'), { target: { value: '[]' } })
 expect(form.getByRole('status')).toHaveTextContent('Configuration changed')
 expect(form.getByRole('status')).not.toHaveTextContent('passed')
 fireEvent.click(form.getByRole('button', { name: 'Cancel' }))
 expect(remote.save).not.toHaveBeenCalled()
 expect(remote.probe).not.toHaveBeenCalled()
 expect(remote.setEnabled).not.toHaveBeenCalled()
})

it('probes the current remote draft with header references, independently of saved connection testing', async () => {
 const remote = api()
 remote.probeDraft = vi.fn(async () => ({ ok: true, value: { tools: [], evidence: { at: 1, status: 'failed', message: '无法连接目标服务，请检查地址、端口与网络。' } } }))
 render(<McpCenterSection api={remote} />)
 fireEvent.click(await screen.findByRole('button', { name: '添加连接' }))
 fireEvent.click(screen.getByRole('button', { name: /远程服务/ }))
 const form = within(screen.getByRole('form', { name: '连接配置' }))
 fireEvent.change(form.getByLabelText('连接名称'), { target: { value: '远程草稿' } })
 fireEvent.change(form.getByLabelText('服务地址'), { target: { value: 'https://example.invalid/mcp' } })
 fireEvent.change(form.getByLabelText('请求头 → 宿主凭证引用（JSON）'), { target: { value: '{"Authorization":"MY_TOKEN"}' } })
 fireEvent.click(form.getByRole('button', { name: '测试连接' }))
 await waitFor(() => expect(form.getByRole('status')).toHaveTextContent('当前配置测试失败'))
 expect(remote.probeDraft).toHaveBeenCalledWith({ configuration: expect.objectContaining({ transport: 'streamable-http', url: 'https://example.invalid/mcp', headerRefs: { Authorization: 'MY_TOKEN' } }) })
 expect(remote.save).not.toHaveBeenCalled()
})
